## Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]

set_property PACKAGE_PIN U17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

##VGA Connector
set_property PACKAGE_PIN G19 [get_ports {vgaRed[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[0]}]
set_property PACKAGE_PIN H19 [get_ports {vgaRed[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[1]}]
set_property PACKAGE_PIN J19 [get_ports {vgaRed[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[2]}]
set_property PACKAGE_PIN N19 [get_ports {vgaRed[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[3]}]
set_property PACKAGE_PIN N18 [get_ports {vgaBlue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[0]}]
set_property PACKAGE_PIN L18 [get_ports {vgaBlue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[1]}]
set_property PACKAGE_PIN K18 [get_ports {vgaBlue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[2]}]
set_property PACKAGE_PIN J18 [get_ports {vgaBlue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[3]}]
set_property PACKAGE_PIN J17 [get_ports {vgaGreen[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[0]}]
set_property PACKAGE_PIN H17 [get_ports {vgaGreen[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[1]}]
set_property PACKAGE_PIN G17 [get_ports {vgaGreen[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[2]}]
set_property PACKAGE_PIN D17 [get_ports {vgaGreen[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[3]}]
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property PACKAGE_PIN R19 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]

## 7 segment
set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[0]}]
set_property PACKAGE_PIN W4 [get_ports {AN[3]}]
set_property PACKAGE_PIN V4 [get_ports {AN[2]}]
set_property PACKAGE_PIN U4 [get_ports {AN[1]}]
set_property PACKAGE_PIN U2 [get_ports {AN[0]}]
set_property PACKAGE_PIN W7 [get_ports {SEG[6]}]
set_property PACKAGE_PIN W6 [get_ports {SEG[5]}]
set_property PACKAGE_PIN U8 [get_ports {SEG[4]}]
set_property PACKAGE_PIN V8 [get_ports {SEG[3]}]
set_property PACKAGE_PIN U5 [get_ports {SEG[2]}]
set_property PACKAGE_PIN V5 [get_ports {SEG[1]}]
set_property PACKAGE_PIN U7 [get_ports {SEG[0]}]

## USB Mouse
set_property IOSTANDARD LVCMOS33 [get_ports PS2_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_DATA]
set_property PACKAGE_PIN C17 [get_ports PS2_CLK]
set_property PACKAGE_PIN B17 [get_ports PS2_DATA]

# DEBUG: DNN ans
# set_property IOSTANDARD LVCMOS33 [get_ports {dnn_ans[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {dnn_ans[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {dnn_ans[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {dnn_ans[3]}]
# set_property PACKAGE_PIN P3 [get_ports {dnn_ans[0]}]
# set_property PACKAGE_PIN N3 [get_ports {dnn_ans[1]}]
# set_property PACKAGE_PIN P1 [get_ports {dnn_ans[2]}]
# set_property PACKAGE_PIN L1 [get_ports {dnn_ans[3]}]

# GAME: ANSWER
set_property IOSTANDARD LVCMOS33 [get_ports {answer[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer[0]}]
set_property PACKAGE_PIN U16 [get_ports {answer[12]}]
set_property PACKAGE_PIN E19 [get_ports {answer[13]}]
set_property PACKAGE_PIN U19 [get_ports {answer[14]}]
set_property PACKAGE_PIN V19 [get_ports {answer[15]}]
set_property PACKAGE_PIN W18 [get_ports {answer[8]}]
set_property PACKAGE_PIN U15 [get_ports {answer[9]}]
set_property PACKAGE_PIN U14 [get_ports {answer[10]}]
set_property PACKAGE_PIN V14 [get_ports {answer[11]}]
set_property PACKAGE_PIN V13 [get_ports {answer[4]}]
set_property PACKAGE_PIN V3 [get_ports {answer[5]}]
set_property PACKAGE_PIN W3 [get_ports {answer[6]}]
set_property PACKAGE_PIN U3 [get_ports {answer[7]}]
set_property PACKAGE_PIN P3 [get_ports {answer[0]}]
set_property PACKAGE_PIN N3 [get_ports {answer[1]}]
set_property PACKAGE_PIN P1 [get_ports {answer[2]}]
set_property PACKAGE_PIN L1 [get_ports {answer[3]}]
